#!/bin/bash

# Creating program to add date/time to log output
adddate() {
    while IFS= read -r line; do
        printf '%s %s\n' "$(date)" "$line";
    done
}

########PLEX INSTALL/UPDATE MANUAL########
function PLEX_INSTALL_UPDATE_MANUAL {

rm -r /tmp/plex_install |& adddate >> /var/log/Plex_Plus
mkdir /tmp/plex_install |& adddate >> /var/log/Plex_Plus

read -p "Enter Plex download URL:" PLEX_URL

wget -P /tmp/plex $PLEX_URL |& adddate >> /var/log/Plex_Plus

sudo dpkg -i /tmp/plex/plexmediaserver*.deb |& adddate >> /var/log/Plex_Plus

sudo systemctl enable plexmediaserver.service |& adddate >> /var/log/Plex_Plus
sudo systemctl start plexmediaserver.service |& adddate >> /var/log/Plex_Plus

rm -r /tmp/plex_install |& adddate >> /var/log/Plex_Plus

}

########PLEX INSTALL VIA REPO - UBUNTU SERVER 18.04########
function PLEX_INSTALL_VIA_REPO {

curl https://downloads.plex.tv/plex-keys/PlexSign.key | sudo apt-key add - |& adddate >> /var/log/Plex_Plus

echo deb https://downloads.plex.tv/repo/deb public main | sudo tee /etc/apt/sources.list.d/plexmediaserver.list |& adddate >> /var/log/Plex_Plus

apt install -y apt-transport-https |& adddate >> /var/log/Plex_Plus
apt update |& adddate >> /var/log/Plex_Plus
apt install -y plexmediaserver |& adddate >> /var/log/Plex_Plus

systemctl enable plexmediaserver |& adddate >> /var/log/Plex_Plus
systemctl start plexmediaserver |& adddate >> /var/log/Plex_Plus

}

########PLEX UPDATE VIA REPO - UBUNTU SERVER 18.04 (OPTION ABOVE HAS TO BE RAN FIRST TO ADD REPO)########
function PLEX_UPDATE_VIA_REPO {

apt update |& adddate >> /var/log/Plex_Plus
apt --only-upgrade install -y plexmediaserver |& adddate >> /var/log/Plex_Plus

systemctl restart plexmediaserver |& adddate >> /var/log/Plex_Plus

}

########XTEVE INSTALL########
function XTEVE_INSTALL {

rm -r /tmp/xteve |& adddate >> /var/log/Plex_Plus
rm -r /usr/local/xteve |& adddate >> /var/log/Plex_Plus
mkdir /tmp/xteve |& adddate >> /var/log/Plex_Plus

echo 'Go to https://xteve.de/ and right click on the distribution that you want to install and select "copy link address".'

read -p "Enter xTeve download URL:" XTEVE_URL

wget -P /tmp/xteve $XTEVE_URL |& adddate >> /var/log/Plex_Plus

apt install -y unzip |& adddate >> /var/log/Plex_Plus

mkdir /usr/local/xteve |& adddate >> /var/log/Plex_Plus

unzip /tmp/xteve/xteve* -d /usr/local/xteve/ |& adddate >> /var/log/Plex_Plus

rm -r /tmp/xteve |& adddate >> /var/log/Plex_Plus

chmod +x /usr/local/xteve/xteve |& adddate >> /var/log/Plex_Plus

read -p "Enter User for systemd xTeve service (needs to have priviledged rights):" service_user
read -p "Enter Group for systemd xTeve service (needs to have priviledged rights):" service_group

rm /etc/systemd/system/xteve.service

echo "

[Unit]
Description=xTeVe Service
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/xteve/xteve 
ExecReload=/usr/bin/killall xteve
ExecStop=/usr/bin/killall xteve
KillMode=process
Restart=always
RestartSec=15

" >/etc/systemd/system/xteve.service

echo User=$service_user  >>/etc/systemd/system/xteve.service
echo Group=$service_group  >>/etc/systemd/system/xteve.service

echo "

[Install]
WantedBy=multi-user.target

" >>/etc/systemd/system/xteve.service

systemctl enable xteve.service |& adddate >> /var/log/Plex_Plus
systemctl start xteve.service |& adddate >> /var/log/Plex_Plus

}

while true ; do
    echo "What would you like to do?"
    echo ""
    echo ""
    echo "1. Plex Install or Update Manually"
    echo "2. Install Plex via REPO"
    echo "3. Update Plex via REPO (Must have run above option previously)"
    echo "4. Install xTeve"
    echo "5. Exit"

    read INPUT
    if [ $INPUT -eq 1 ] ; then 2>/dev/null
        echo "Installing or Updating Plex"
        echo "..."
        PLEX_INSTALL_UPDATE_MANUAL

    elif [ $INPUT -eq 2 ] ; then 2>/dev/null
        echo "Installing Plex via Repo"
        echo "..."
        PLEX_INSTALL_VIA_REPO

    elif [ $INPUT -eq 3 ] ; then 2>/dev/null
        echo "Updating Plex Via Repo"
        echo "..."
        PLEX_UPDATE_VIA_REPO

    elif [ $INPUT -eq 4 ] ; then 2>/dev/null
        echo "Installing xTeve"
        echo "..."
        XTEVE_INSTALL

    elif [ $INPUT -eq 5 ] ; then 2>/dev/null
		echo "Exiting"
		echo "..."
        exit 0
    else
        echo "invalid choice"
    fi
done
